
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxigocnatqgqgiedrgue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4aWdvY25hdHFncWdpZWRyZ3VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTY1ODgsImV4cCI6MjA2MDgzMjU4OH0.JaRFyEuVOC9VXoPFc7ohO77F1qM_NwY_jOgNcSacfp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Create a user record in the users table
export const createUserRecord = async (userId: string, userData: {
  Name: string;
  Email: string;
  Password: string;
  Phone: string;
  Country: string;
  Activate: string;
  Block: string;
  Credits: string;
  User_Type: string;
  Email_Type: string;
  Expiry_Time: string;
  Start_Date: string;
  Hwid: string;
  UID: string;
}) => {
  // Map to the Supabase schema field names
  const { data, error } = await supabase.from('users').insert({
    id: userId,
    name: userData.Name,
    email: userData.Email,
    password: userData.Password,
    phone: userData.Phone,
    country: userData.Country,
    activate: userData.Activate,
    block: userData.Block,
    credits: userData.Credits,
    user_type: userData.User_Type,
    email_type: userData.Email_Type,
    expiry_time: userData.Expiry_Time,
    start_date: userData.Start_Date,
    hwid: userData.Hwid,
    uid: userData.UID
  });

  if (error) {
    console.error("Error creating user record:", error);
    throw error;
  }

  return data;
};
